### PR TITLE
Hack for ArteDigital

### PR DESCRIPTION
**Pull request by enriqueojedalara**
Customization

### CODE REVIEW

**Comment by enriqueojedalara** [comment]
Wrong pull request (Should be local)

**Comment by aullman** [comment]
Are you using opentok-meet? Why can't you just remove the draggable attribute from the facePublisher if you don't want it to drag?

**Comment by enriqueojedalara** [comment]
Yes, but was weird we were removing the attribute but it did not work, probably because other conflict in our code, we just added the very ugly hack because we are rush, I need to check it again to see what was our error with more time; Thanks a lot the code is really good.

**Comment by aullman** [comment]
Strange, removing the draggable attribute should stop the draggable directive from being added to the component which is what's adding the dragging functionality. https://github.com/aullman/opentok-meet/blob/master/public/js/directives.js#L1

**Comment by enriqueojedalara** [comment]
At the end found the problem and removing draggable works perfectly, thanks a lot!

**Pull request closed without merging**
