### PR TITLE
broadcast events

### PR DESCRIPTION
**Pull request by papaloizouc**
hi would it make sense to broadcast events?

### CODE REVIEW

**Comment by aullman** [comment]
Yep, totally makes sense, thanks @papaloizouc. Could you update the version to 0.4.0 to stick to semver and then I'll approve it.

**Comment by papaloizouc** [comment]
great thanks, i updated the version and the docs as well.

**Comment by aullman** [comment]
Come to think of it @papaloizouc should it be `$emit` instead of `$broadcast`? What is it that you are using this for? You can also use the callback in `OTSession.init` to get a handle on the session object and listen for these events https://github.com/aullman/opentok-angular#example-usage

**Comment by papaloizouc** [comment]
hi it turns out it may not be needed i was not sure that's why i asked if it makes sense.

My concern was that you can't listen on `sessionConnected` event because inside the callback the session is already connected so the only way to get that event is to broadcast/emit it. So i thought if a connection is made before you register `session.on('connectionCreated')` in the callback you won't get the event (OTSession factory registers the events before connecting) but it seems to be working fine.

**Pull request closed without merging**
